version: "3"
networks:
        monitor-net:
                ipam:
                        driver: default
                        config:
                        - subnet: 172.20.0.0/16

services:
        hue-exporter:
                image: mitchellrj/hue_exporter:latest-arm7
                expose:
                        - "9366"
                container_name: hue-exporter
                volumes:
                        - ./hue-exporter-config.yml:/etc/hue_exporter/config.yml
                restart: unless-stopped
                networks:
                        - monitor-net

        prometheus:
                image: rycus86/prometheus:armhf
                ports:
                        - "4000:9090"
                container_name: prometheus
                volumes:
                        - $PWD/data/prometheus:/prometheus
                        - ./prometheus.yml:/etc/prometheus/prometheus.yml
                restart: unless-stopped
                networks:
                        - monitor-net
                extra_hosts:
                        - "dockerhost:172.20.0.1"

        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
                container_name: grafana
                volumes:
                        - ./data/grafana:/var/lib/grafana/
                restart: unless-stopped
                user: "1001:1001"
                networks:
                        - monitor-net

        temp-exporter:
                image: carlosedp/arm_exporter
                container_name: temp-exporter
                expose: 
                        - "9243"
                ports:
                        - "9243:9243"
                restart: unless-stopped
                networks:
                        - monitor-net
