version: "3"
networks:
  monitor-net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  hue-exporter:
    image: mitchellrj/hue_exporter:latest-arm7
    expose:
      - "9366"
    container_name: hue-exporter
    volumes:
      - ./hue-exporter-config.yml:/etc/hue_exporter/config.yml
    restart: unless-stopped
    networks:
      - monitor-net

  prometheus:
    image: quay.io/prometheus/prometheus:v2.43.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=400d"
    ports:
      - "4000:9090/tcp"
    container_name: prometheus
    volumes:
      - $PWD/data/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitor-net
    extra_hosts:
      - "dockerhost:172.20.0.1"

  grafana:
    image: grafana/grafana:8.5.22
    ports:
      - "3000:3000"
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana/
    restart: unless-stopped
    user: "1001:1001"
    networks:
      - monitor-net

  temp-exporter:
    image: carlosedp/arm_exporter
    container_name: temp-exporter
    expose:
      - "9243"
    ports:
      - "9243:9243"
    restart: unless-stopped
    networks:
      - monitor-net

  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/deCONZ"
    devices:
      - /dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=1702
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
      - DECONZ_START_VERBOSE=0
    restart: unless-stopped
    privileged: true
