version: "3"
networks:
        monitor-net:
                driver: bridge

services:
        hue-exporter:
                image: mitchellrj/hue_exporter:latest-arm7
                expose:
                        - "9366"
                container_name: hue-exporter
                volumes:
                        - ./hue-exporter-config.yml:/etc/hue_exporter/config.yml
                restart: unless-stopped
                networks:
                        - monitor-net

        prometheus:
                image: rycus86/prometheus:armhf
                ports:
                        - "4000:9090"
                container_name: prometheus
                volumes:
                        - $PWD/data/prometheus:/prometheus
                        - ./prometheus.yml:/etc/prometheus/prometheus.yml
                restart: unless-stopped
                networks:
                        - monitor-net

        grafana:
                image: grafana/grafana
                ports:
                        - "3000:3000"
                container_name: grafana
                volumes:
                        - ./data/grafana:/var/lib/grafana/
                restart: unless-stopped
                user: "1001:1001"
                networks:
                        - monitor-net

        node-exporter:
                image: prom/node-exporter:latest
                user: root
                privileged: true
                container_name: node-exporter
                volumes:
                        - /proc:/host/proc:ro
                        - /sys:/host/sys:ro
                        - /:/rootfs:ro
                command:
                        - '--path.procfs=/host/proc'
                        - '--path.sysfs=/host/sys'
                        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
                restart: unless-stopped
                expose:
                        - "9100"
                networks:
                        - monitor-net
