version: "3"
services:
        plex:
                image: linuxserver/plex:latest
                container_name: plex
                network_mode: host
                environment:
                        - PUID=1001
                        - PGID=1001
                        - VERSION=docker
                        - UMASK_SET=022 #optional
                        - PLEX_CLAIM= #optional
                volumes:
                        - ./data/plex:/config
                        - /media/hdd/Series:/tv
                        - /media/hdd/Movies:/movies
                restart: unless-stopped
