ip_address: 192.168.0.10
api_key: "<ADD_YOUR_SECRET_TOKEN_HERE>"
sensors:
  # With `match_names` set, the exporter will set the names of temperature
  # sensors and light level sensors to that of the motion sensor (the one that
  # you've actually configured in the Hue app)
  match_names: true
  ignore_types:
  - CLIPGenericStatus
