global:
    scrape_interval:     15s
    evaluation_interval: 30s

scrape_configs:
    - job_name: 'raspberry'
      static_configs:
        - targets: ['192.168.0.222:9100']

    - job_name: 'hue'
      scrape_interval: 10s
      static_configs:
              - targets: ['192.168.0.222:9000']
