global:
    scrape_interval:     15s
    evaluation_interval: 30s

scrape_configs:
    - job_name: 'raspberry'
      static_configs:
              # dockerhost is the hostname which is available in the prometheus container
              - targets: ['dockerhost:9100']

    - job_name: 'hue'
      scrape_interval: 10s
      static_configs:
              - targets: ['hue-exporter:9366']
                
    - job_name: 'processes'
      static_configs:
              - targets: ['dockerhost:9256']
                
    - job_name: 'raspberry-temperature'
      static_configs:
              - targets: ['temp-exporter:9243']
                
    - job_name: 'deconz'
      static_configs:
              - targets: ['dockerhost:2112']
