global:
    scrape_interval:     15s
    evaluation_interval: 30s

scrape_configs:
    - job_name: 'raspberry'
      static_configs:
              - targets: ['node-exporter:9100']

    - job_name: 'hue'
      scrape_interval: 10s
      static_configs:
              - targets: ['hue-exporter:9366']
