{
 "title": "Hue",
 "description": "Residence's Hue monitoring",
 "tags": [
  "Philips Hue",
  "Lights"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Light level",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Lights On" }
   ],
   "targets": [
    { "expr": "hue_light_on", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Rooms",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "hue_group_on{type=\"Room\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Battery levels",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "min(hue_sensor_battery{type=~\"(ZLLPresence|ZLLSwitch)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Brightness Settings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Brightness" }
   ],
   "targets": [
    { "expr": "hue_light_brightness/255", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Reachability Errors",
   "type": "graph",
   "description": "Displays the occurrence of errors when trying to contact Philips Hue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hue_light_scrapes_failed", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hue_sensor_value{type=\"ZLLTemperature\"} / 100",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}